### ISSUE TITLE
SA1029: should not use built-in type int as key for value; define your own type to avoid collisions (staticcheck)

### ISSUE THREAD

**Issue by volnt** [clerk/clerk-sdk-go#170]
Hello 👋 

I'm creating an issue to track

> SA1029: should not use built-in type int as key for value; define your own type to avoid collisions (staticcheck)

I see that this issue has already been identified (see https://github.com/clerkinc/clerk-sdk-go/blob/main/clerk/middleware.go#L13-L14) but it's not tracked as an issue.

Ideally we'd want to have a type alias instead of int, because the current implementation allows for Context collision.

**Comment by gkats** [comment]
Hi @volnt, thanks for calling this out!

This issue has been fixed in our [v2 version of the Go SDK](https://github.com/clerk/clerk-sdk-go/tree/v2). We'd love for you to check it out!
