### ISSUE TITLE
VerifyToken performance

### ISSUE THREAD

**Issue by balsamic-r** [clerk/clerk-sdk-go#172]
Hello everyone, I apologize for my poor English. I don't use Golang often, and I wanted to ask if it's normal that this function 

`client.VerifyToken(sessionToken)`

takes about 500ms

**Comment by dimkl** [comment]
Hello @balsamic-r 👋 
Could you provide a completion reason? Eg what was the issue for the 500ms performance issue and how did you resolve it?
