### ISSUE TITLE
Retries in http client

### ISSUE THREAD

**Issue by Hades32** [clerk/clerk-sdk-go#194]
Transient errors are inevitable and therefore for most of our http clients we use a retrying http client (in our case `hashicorp/go-retryablehttp`, but that shouldn't matter).

But with Clerk we neither can provide such a client (as you're using an exact type for the http client instead of an interface), nor does your SDK itself allow to retry transient errors.

As you're only using a single method of the client, changing it to an interface should be a quick win

**Comment by georgepsarakis** [comment]
Hello @Hades32 ! You can pass a custom HTTP client using the `WithHTTPClient` constructor option:

https://github.com/clerk/clerk-sdk-go/blob/d95ad77752e58cb74b816aa609ec5357aa4ed4ee/clerk/clerk_options.go#L12

Example with `go-retryablehttp`:

```go
// Taken from https://github.com/hashicorp/go-retryablehttp/#getting-a-stdlib-httpclient-with-retries
retryClient := retryablehttp.NewClient()
retryClient.RetryMax = 10

standardClient := retryClient.StandardClient() // *http.Client

clerkSDKClient := clerk.NewClient(token, clerk.WithHTTPClient(standardClient))
```

Would this approach solve the issue you're facing? Happy to explain further if needed!

**Comment by georgepsarakis** [comment]
Sounds good and thanks again for bringing this to our attention, it's definitely an interesting topic. I'll also go ahead and document the `http.Client` injection option to provide broader visibility, as your use case of integrating with `go-retryablehttp` makes perfect sense. We'll also keep the interface suggestion in mind for future versions!
