### ISSUE TITLE
Adds middleware support for Gin Web Framework 

### ISSUE THREAD

**Issue by darul75** [clerk/clerk-sdk-go#197]
Hi team,

Really great product so far.

Using the Gin framework I had to adapt the Go SDK so it can better support the integration of Clerk through a middleware.

I went through your code and adapted it at minima so it can work.

You can find it there https://gist.github.com/darul75/e2b233d8c2cf8bf7518169bac5023a81

Would you like me to raise a PR and also get merged some common logic or does it make sense to keep it separated so you do not need this extra gin dependency.

Thanks in advance,
Julien

**Comment by zstatmanweil** [comment]
I used this for my project and it is working great so far! I might also suggest adding this function since Gin context expects string keys and doesn't work with the existing `SessionFromContext`:

```go
func SessionFromContextGin(ctx *gin.Context) (*clerk.SessionClaims, bool) {
	c, ok := ctx.Value(ACTIVE_SESSION_CLAIMS).(*clerk.SessionClaims)
	return c, ok
}
```

**Comment by KTAppDev** [comment]
Thank you so much for this

**Comment by gusgita** [comment]
This is really helpful. Thank you for this.

**Comment by gkats** [comment]
Coming a bit late to the discussion, @darul75 thank you for providing your snippet! :heart: 

Supporting specific Go frameworks is unfortunately out of scope for the Clerk Go SDK. We would be interested in providing the right abstractions for making framework integration easier however.

I'll go ahead and close this issue, but I'm glad it helps more people using Gin. :raised_hands:

**Comment by darul75** [comment]
> Coming a bit late to the discussion, @darul75 thank you for providing your snippet! ❤️
> 
> Supporting specific Go frameworks is unfortunately out of scope for the Clerk Go SDK. We would be interested in providing the right abstractions for making framework integration easier however.
> 
> I'll go ahead and close this issue, but I'm glad it helps more people using Gin. 🙌

You are welcome.

**Comment by AlvaroParker** [comment]
This is working for me: 

```go
import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func AdaptClerkMiddleware(clerkMiddleware func(http.Handler) http.Handler) gin.HandlerFunc {
	return func(c *gin.Context) {
		var handlerCalled bool

		wrappedHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			handlerCalled = true
			c.Request = r
			c.Next()
		})

		clerkMiddleware(wrappedHandler).ServeHTTP(c.Writer, c.Request)

		if !handlerCalled {
			c.Abort()
		}
	}
}
```

Then you can use it like this:

```go
import (
	clerkhttp "github.com/clerk/clerk-sdk-go/v2/http"
)
func main() {
	router := gin.Default()

	authorized := router.Group("/")
	authorized.Use(handlers.AdaptClerkMiddleware(clerkhttp.RequireHeaderAuthorization()))
	{
		// Secure hello world
		authorized.GET("/api/hello-secure", handlers.HandleHello)
	}

	// ... more code
}
```

Session claims can we recovered as well on a gin handler, for example, I use this function to retrieve the user:

```go
package util

import (
	"log"

	"github.com/clerk/clerk-sdk-go/v2"
	"github.com/clerk/clerk-sdk-go/v2/user"
	"github.com/gin-gonic/gin"
)

func RetrieveUser(ctx *gin.Context) (*clerk.User, bool) {
	c := ctx.Request.Context()
	claims, ok := clerk.SessionClaimsFromContext(c)
	if !ok {
		return nil, false
	}
	user, usrErr := user.Get(c, claims.Subject)
	if usrErr != nil {
		log.Println("Error retrieving user:", usrErr)
		return nil, false
	}

	return user, true
}
```
