### ISSUE TITLE
Update Private Metadata is not working with Go SDK

### ISSUE THREAD

**Issue by ankushChatterjee** [clerk/clerk-sdk-go#325]
Here is the code I am using.
```
	user, err = clerkClient.Users().UpdateMetadata("user_2m9YOsxInz5QXCybr0NIbeu5xxx", &clerk.UpdateUserMetadata{
		PublicMetadata: []byte(`{"email":"john@example.com"}`),
	})

```

This call returns no error. However, the metadata is not updated on dashboard.

**Comment by chanioxaris** [comment]
Hello @ankushChatterjee, we have released a new version v2 of the SDK where the issue has been resolved. You can find it [here](https://github.com/clerk/clerk-sdk-go/tree/v2) along with an [upgrade guide](https://github.com/clerk/clerk-sdk-go/blob/v2/UPGRADING.md#1-x-x-to-2-x-x). Do you mind to test it out and let us know if it's not a lot of trouble?

**Comment by ankushChatterjee** [comment]
Thanks, that is working.
