### ISSUE TITLE
Signintoken module is not present in latest package (	"github.com/clerk/clerk-sdk-go/v2")

### ISSUE THREAD

**Issue by MohamedArif20091999** [clerk/clerk-sdk-go#344]
I'm trying to do signintoken.Create() . But it is not available in the package. Can someone help me in understanding what am I missing? Or I'm doing in a wrong way

**Comment by gkats** [comment]
Hi, @MohamedArif20091999 the Sign in token API should be available in version [v2.1.0](https://pkg.go.dev/github.com/clerk/clerk-sdk-go/v2@v2.1.0) upwards.

We hadn't tagged a new release and that's probably why you couldn't use the API.

Please feel free to reopen the issue if that still doesn't work for you.

**Comment by MohamedArif20091999** [comment]
Thanks , it worked @gkats
