### ISSUE TITLE
Update go-jose to 3.0.3 to resolve security issue

### ISSUE THREAD

**Issue by davidmytton** [clerk/clerk-sdk-go#346]
Do you plan to merge https://github.com/clerk/clerk-sdk-go/pull/300 and update go-jose from `3.0.1` to `3.0.3`? Although v4 is the latest version, security fixes are still being backported and https://github.com/go-jose/go-jose/releases/tag/v3.0.3 includes a fix for https://github.com/advisories/GHSA-c5q2-7r4c-mv6g

**Comment by gkats** [comment]
Hi @davidmytton, 

Thanks for the nudge. The PR is now merged and go-jose should be bumped to 3.0.3 now. The release tag is [v2.1.0](https://pkg.go.dev/github.com/clerk/clerk-sdk-go/v2@v2.1.0).

I guess we should look into upgrading to v4 at some point.
